#' Plot a hanesch type plot based on a summary of ROI innervation
#' @param roiTable A table of ROI innervation, as generated by \code{\link{getROISummary}}
#' @param roiSelect A selection of ROIs table, as generated by \code{\link{selectRoiSet}}
#' @param grouping A string of grouping variable(s) of \code{roiTable} to facet the plot on.
#' Will usually be one of the \code{supertype} columns
#' @param flip Flip the x/y axis? If TRUE, types will be on the bottom axis and ROIs on the
#' side axis
#' @param alphaRois The alpha of the color rectangles coding the ROIs
#' @param roiLabel A selection of ROIs, as generated by \code{\link{selectRoiSet}} to be used for the ROI color guide
#' @param regionOutlines Whether or not to add the ROI color code
#' @param theme Theme to be passed to ggplot2
#' @param interactive Whether or not to use some interactivity from ggiraph
#'
#' @export
haneschPlot <- function(roiTable,
                        roiSelect=selectRoiSet(getRoiTree()),
                        grouping=NULL,flip=FALSE,
                        alphaRois=0.15,
                        roiLabel=selectRoiSet(getRoiTree(),default_level = 0),
                        regionOutlines=TRUE,
                        theme=theme_minimal(),
                        interactive=FALSE){
  roiTable <- roiTable %>% filter(roi %in% unique(roiSelect$roi))  %>%
    mutate(roi = factor(roi,levels=levels(roiSelect$roi)),
           l4 = roiSelect$level4[match(roi,roiSelect$roi)],
           side = roiSelect$side2[match(roi,roiSelect$roi)],
           superroi = roiLabel$roi[match(l4,roiLabel$level4)]) %>%
    arrange(roi) %>%
    mutate(roiX = match(roi,unique(roi)))

  roiPos <- roiTable %>% group_by(superroi,side) %>%
    summarize(xmin=min(roiX)-0.45,xmax=max(roiX)+0.45) %>%
    ungroup() #%>%
  #filter(xmax-xmin>1)

  hanesch <- ggplot(data=roiTable,aes(x=roi,y=type))
  roiP <- roisPalette()

  hanesch <- hanesch +
    geom_line(aes(group=type))
  if (regionOutlines==TRUE){hanesch <- hanesch +
    geom_rect(data=roiPos,aes(xmin=xmin,xmax=xmax,ymin=-Inf,ymax=Inf,fill=superroi),alpha=alphaRois,inherit.aes = F) +
    scale_fill_manual(name="Brain region",values=roiP,guide = guide_legend(reverse = TRUE)) +
    ggnewscale::new_scale_fill()}
  if (interactive){
    hanesch <- hanesch + ggiraph::geom_point_interactive(data=roiTable,aes(size=fullWeight,fill=deltaWeight,x=roi,y=type,tooltip=paste0(type," in ",roi,"\nOutputs: ",OutputWeight,"\nInputs: ",InputWeight)),shape=21)}
  else{
    hanesch <- hanesch +
      geom_point(data=roiTable,aes(size=fullWeight,fill=deltaWeight,x=roi,y=type),shape=21)}
  hanesch <- hanesch +
    scale_fill_gradient(name="Polarity",breaks=c(-1,-0.5,0,0.5,1),labels=c("Receives inputs","","Mixed","","Sends outputs"),low = "white", high = "black",
                        space = "Lab") +
    guides(fill = guide_legend(override.aes = list(size=5))) +
    scale_size_continuous(name = "# Synapses") + labs(y="Neuron type",x="Neuropile") + theme

  if (!(is.null(grouping))){
    if (flip==TRUE){fct <- paste(". ~",grouping)}else{fct <- paste(grouping,"~ .")}
    hanesch <- hanesch + facet_grid(as.formula(fct),scale="free",space="free")
  }

  if (flip==TRUE){hanesch <- hanesch + coord_flip()}
  hanesch + theme(axis.text.x = element_text(angle = 90))

}
